# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrip.proto\x12\x04trip\"\x07\n\x05\x45mpty\"(\n\x11\x43reateTripRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\"/\n\x0cTripResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\"\'\n\x04Trip\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\"-\n\x10TripListResponse\x12\x19\n\x05trips\x18\x01 \x03(\x0b\x32\n.trip.Trip2z\n\x0bTripService\x12\x39\n\nCreateTrip\x12\x17.trip.CreateTripRequest\x1a\x12.trip.TripResponse\x12\x30\n\tListTrips\x12\x0b.trip.Empty\x1a\x16.trip.TripListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CREATETRIPREQUEST']._serialized_start=29
  _globals['_CREATETRIPREQUEST']._serialized_end=69
  _globals['_TRIPRESPONSE']._serialized_start=71
  _globals['_TRIPRESPONSE']._serialized_end=118
  _globals['_TRIP']._serialized_start=120
  _globals['_TRIP']._serialized_end=159
  _globals['_TRIPLISTRESPONSE']._serialized_start=161
  _globals['_TRIPLISTRESPONSE']._serialized_end=206
  _globals['_TRIPSERVICE']._serialized_start=208
  _globals['_TRIPSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
