# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wiki.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wiki.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwiki.proto\x12\x07wiki.v1\"\x8c\x01\n\x15GetPlaceBriefsRequest\x12\x11\n\tplace_ids\x18\x01 \x03(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12$\n\x06length\x18\x03 \x01(\x0e\x32\x14.wiki.v1.BriefLength\x12#\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x13.wiki.v1.TextFormat\"[\n\tMediaItem\x12\x0b\n\x03url\x18\x01 \x01(\t\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.wiki.v1.MediaType\x12\x0f\n\x07\x63\x61ption\x18\x03 \x01(\t\x12\x0e\n\x06\x63redit\x18\x04 \x01(\t\"\x9f\x01\n\nPlaceBrief\x12\x10\n\x08place_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0csummary_text\x18\x03 \x01(\t\x12\x18\n\x10\x66ull_details_url\x18\x04 \x01(\t\x12\x16\n\x0emain_image_url\x18\x05 \x01(\t\x12)\n\rgallery_media\x18\x06 \x03(\x0b\x32\x12.wiki.v1.MediaItem\"T\n\x16GetPlaceBriefsResponse\x12#\n\x06\x62riefs\x18\x01 \x03(\x0b\x32\x13.wiki.v1.PlaceBrief\x12\x15\n\rnot_found_ids\x18\x02 \x03(\t*\\\n\x0b\x42riefLength\x12\x1c\n\x18\x42RIEF_LENGTH_UNSPECIFIED\x10\x00\x12\x16\n\x12\x42RIEF_LENGTH_SHORT\x10\x01\x12\x17\n\x13\x42RIEF_LENGTH_MEDIUM\x10\x02*V\n\nTextFormat\x12\x1b\n\x17TEXT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n\x11TEXT_FORMAT_PLAIN\x10\x01\x12\x14\n\x10TEXT_FORMAT_HTML\x10\x02*l\n\tMediaType\x12\x1a\n\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n\x10MEDIA_TYPE_VIDEO\x10\x02\x12\x17\n\x13MEDIA_TYPE_PANORAMA\x10\x03\x32`\n\x0bWikiService\x12Q\n\x0eGetPlaceBriefs\x12\x1e.wiki.v1.GetPlaceBriefsRequest\x1a\x1f.wiki.v1.GetPlaceBriefsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wiki_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRIEFLENGTH']._serialized_start=507
  _globals['_BRIEFLENGTH']._serialized_end=599
  _globals['_TEXTFORMAT']._serialized_start=601
  _globals['_TEXTFORMAT']._serialized_end=687
  _globals['_MEDIATYPE']._serialized_start=689
  _globals['_MEDIATYPE']._serialized_end=797
  _globals['_GETPLACEBRIEFSREQUEST']._serialized_start=24
  _globals['_GETPLACEBRIEFSREQUEST']._serialized_end=164
  _globals['_MEDIAITEM']._serialized_start=166
  _globals['_MEDIAITEM']._serialized_end=257
  _globals['_PLACEBRIEF']._serialized_start=260
  _globals['_PLACEBRIEF']._serialized_end=419
  _globals['_GETPLACEBRIEFSRESPONSE']._serialized_start=421
  _globals['_GETPLACEBRIEFSRESPONSE']._serialized_end=505
  _globals['_WIKISERVICE']._serialized_start=799
  _globals['_WIKISERVICE']._serialized_end=895
# @@protoc_insertion_point(module_scope)
