# Generated by Django 4.2.27 on 2026-02-11 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(db_column='comment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('place', 'مکان'), ('event', 'رویداد')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team13_comments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(db_column='event_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'team13_events',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(db_column='image_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('place', 'مکان'), ('event', 'رویداد')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'team13_images',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.UUIDField(db_column='place_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('entertainment', 'تفریحی'), ('food', 'غذا'), ('hospital', 'بیمارستان'), ('museum', 'موزه'), ('hotel', 'هتل')], max_length=32)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'team13_places',
            },
        ),
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('place', models.OneToOneField(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hotel_details', serialize=False, to='team13.place')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_range', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'team13_hotel_details',
            },
        ),
        migrations.CreateModel(
            name='MuseumDetails',
            fields=[
                ('place', models.OneToOneField(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='museum_details', serialize=False, to='team13.place')),
                ('open_at', models.TimeField(blank=True, null=True)),
                ('close_at', models.TimeField(blank=True, null=True)),
                ('ticket_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team13_museum_details',
            },
        ),
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('place', models.OneToOneField(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restaurant_details', serialize=False, to='team13.place')),
                ('cuisine', models.CharField(blank=True, max_length=128)),
                ('avg_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team13_restaurant_details',
            },
        ),
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('travel_mode', models.CharField(choices=[('car', 'خودرو'), ('walk', 'پیاده'), ('transit', 'حمل\u200cونقل عمومی')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_place', models.ForeignKey(db_column='destination_place_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='team13.place')),
                ('source_place', models.ForeignKey(db_column='source_place_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='team13.place')),
            ],
            options={
                'db_table': 'team13_route_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='team13.place')),
            ],
            options={
                'db_table': 'team13_place_translations',
                'unique_together': {('place', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='PlaceAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=128)),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='team13.place')),
            ],
            options={
                'db_table': 'team13_place_amenities',
                'unique_together': {('place', 'amenity_name')},
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='team13.event')),
            ],
            options={
                'db_table': 'team13_event_translations',
                'unique_together': {('event', 'lang')},
            },
        ),
    ]
