# Generated by Django 4.2.27 on 2026-02-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team13', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='target_type',
            field=models.CharField(choices=[('place', 'مکان'), ('event', 'رویداد'), ('pending_place', 'مکان در انتظار تأیید')], max_length=16),
        ),
        migrations.CreateModel(
            name='TeamAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='team13_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team13_team_admins',
            },
        ),
        migrations.CreateModel(
            name='PlaceContribution',
            fields=[
                ('contribution_id', models.UUIDField(db_column='contribution_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('entertainment', 'تفریحی'), ('food', 'غذا'), ('hospital', 'بیمارستان'), ('museum', 'موزه'), ('hotel', 'هتل')], max_length=32)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team13_place_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team13_place_contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
