# Generated by Django 4.2.27 on 2026-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team13', '0002_add_place_contribution_and_team_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamadmin',
            name='user',
        ),
        migrations.AddField(
            model_name='teamadmin',
            name='user_id',
            field=models.CharField(blank=True, db_column='user_id', db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
