# Generated by Django 4.2.27 on 2026-02-12 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team13', '0003_teamadmin_user_id_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteContribution',
            fields=[
                ('contribution_id', models.UUIDField(db_column='contribution_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_address', models.TextField(help_text='آدرس مبدأ (از روی عرض/طول ثابت شده)')),
                ('source_latitude', models.FloatField()),
                ('source_longitude', models.FloatField()),
                ('destination_address', models.TextField(help_text='آدرس مقصد (از روی عرض/طول ثابت شده)')),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('travel_mode', models.CharField(choices=[('car', 'خودرو'), ('walk', 'پیاده'), ('transit', 'حمل\u200cونقل عمومی')], default='car', max_length=16)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team13_route_contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
