# Generated by Django 4.2.27 on 2026-02-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team13', '0005_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('entertainment', 'تفریحی'), ('food', 'غذا'), ('hospital', 'بیمارستان'), ('museum', 'موزه'), ('hotel', 'هتل'), ('fire_station', 'آتش\u200cنشانی'), ('pharmacy', 'داروخانه'), ('clinic', 'کلینیک')], max_length=32),
        ),
        migrations.AlterField(
            model_name='placecontribution',
            name='type',
            field=models.CharField(choices=[('entertainment', 'تفریحی'), ('food', 'غذا'), ('hospital', 'بیمارستان'), ('museum', 'موزه'), ('hotel', 'هتل'), ('fire_station', 'آتش\u200cنشانی'), ('pharmacy', 'داروخانه'), ('clinic', 'کلینیک')], max_length=32),
        ),
    ]
