# Generated by Django 4.2.7 on 2026-02-11 16:25

import data.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('budget_level', models.CharField(choices=[('ECONOMY', 'اقتصادی'), ('MEDIUM', 'معمولی'), ('LUXURY', 'لوکس'), ('UNLIMITED', 'بدون محدودیت')], max_length=15)),
                ('daily_available_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('travel_style', models.CharField(choices=[('SOLO', 'تنها'), ('COUPLE', 'دونفره'), ('FAMILY', 'خانوادگی'), ('FRIENDS', 'با دوستان'), ('BUSINESS', 'کاری')], max_length=15)),
                ('generation_strategy', models.CharField(choices=[('HISTORICAL', 'Historical'), ('ECONOMIC', 'Economic'), ('MIXED', 'Mixed')], max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=15)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copied_from_trip', models.ForeignKey(blank=True, db_column='copied_from_trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.trip')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team11_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sql_trip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('specific_date', models.DateField()),
                ('start_geo_location', models.CharField(blank=True, max_length=100)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='data.trip')),
            ],
            options={
                'db_table': 'sql_trip_day',
                'ordering': ['trip', 'day_index'],
            },
        ),
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('VISIT', 'بازدید'), ('STAY', 'اقامت')], default='VISIT', max_length=10)),
                ('place_ref_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('HISTORICAL', 'تاریخی'), ('NATURAL', 'طبیعی'), ('CULTURAL', 'فرهنگی'), ('RECREATIONAL', 'تفریحی'), ('RELIGIOUS', 'مذهبی'), ('DINING', 'رستوران')], max_length=50)),
                ('address_summary', models.CharField(blank=True, max_length=500)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('wiki_summary', models.TextField(blank=True)),
                ('wiki_link', models.URLField(blank=True)),
                ('main_image_url', models.URLField(blank=True)),
                ('start_time', models.TimeField(validators=[data.models.validate_15_minute_intervals])),
                ('end_time', models.TimeField(validators=[data.models.validate_15_minute_intervals])),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(60)])),
                ('sort_order', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('price_tier', models.CharField(choices=[('FREE', 'رایگان'), ('BUDGET', 'ارزان'), ('MODERATE', 'متوسط'), ('EXPENSIVE', 'گران'), ('LUXURY', 'لوکس')], default='FREE', max_length=15)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transport_mode_to_next', models.CharField(blank=True, choices=[('WALK', 'Walking'), ('TAXI', 'Taxi'), ('BUS', 'Bus'), ('METRO', 'Metro'), ('CAR', 'Personal Car')], max_length=10)),
                ('travel_time_to_next', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_distance_to_next', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.tripday')),
            ],
            options={
                'db_table': 'sql_trip_item',
                'ordering': ['day', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('permission', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Can Edit')], default='VIEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='data.trip')),
            ],
            options={
                'db_table': 'sql_share_link',
            },
        ),
        migrations.CreateModel(
            name='ItemDependency',
            fields=[
                ('dependency_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('FINISH_TO_START', 'Finish-to-Start')], default='FINISH_TO_START', max_length=20)),
                ('violation_action', models.CharField(choices=[('WARN', 'Warning Only'), ('BLOCK', 'Block Action')], default='WARN', max_length=10)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='data.tripitem')),
                ('prerequisite_item', models.ForeignKey(db_column='prerequisite_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='data.tripitem')),
            ],
            options={
                'db_table': 'sql_item_dependency',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_session_id', models.CharField(db_index=True, max_length=128)),
                ('is_upvote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='data.tripitem')),
            ],
            options={
                'db_table': 'sql_vote',
                'indexes': [models.Index(fields=['item', 'guest_session_id'], name='sql_vote_item_id_41106d_idx')],
                'unique_together': {('item', 'guest_session_id')},
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('PANORAMA', 'Panorama')], default='PHOTO', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='data.trip')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='team11_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sql_user_media',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['trip', '-uploaded_at'], name='sql_user_me_trip_id_2801c6_idx'), models.Index(fields=['user', '-uploaded_at'], name='sql_user_me_user_id_44bd6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('sent_to_central_service', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='data.tripitem')),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='data.trip')),
            ],
            options={
                'db_table': 'sql_trip_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip', '-created_at'], name='sql_trip_re_trip_id_3fb609_idx'), models.Index(fields=['item'], name='sql_trip_re_item_id_26f86c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tripitem',
            index=models.Index(fields=['day', 'sort_order'], name='sql_trip_it_day_id_5cf2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitem',
            index=models.Index(fields=['place_ref_id'], name='sql_trip_it_place_r_fd0c93_idx'),
        ),
        migrations.AddIndex(
            model_name='tripday',
            index=models.Index(fields=['trip', 'day_index'], name='sql_trip_da_trip_id_92ebea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together={('trip', 'day_index')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-created_at'], name='sql_trip_user_id_a1330b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['province'], name='sql_trip_provinc_c971ac_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['city'], name='sql_trip_city_789497_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='sql_trip_status_49798c_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='sql_share_l_token_a77dee_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['trip', 'expires_at'], name='sql_share_l_trip_id_884806_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdependency',
            index=models.Index(fields=['item'], name='sql_item_de_item_id_213e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdependency',
            index=models.Index(fields=['prerequisite_item'], name='sql_item_de_prerequ_9c5580_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdependency',
            unique_together={('item', 'prerequisite_item')},
        ),
    ]
