# Generated by Django 5.2.11 on 2026-02-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='density',
            field=models.CharField(blank=True, choices=[('RELAXED', 'آرام'), ('BALANCED', 'متعادل'), ('INTENSIVE', 'فشرده')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINALIZED', 'Finalized'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=15),
        ),
    ]
