# Generated by Django 5.2.11 on 2026-02-13 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_trip_density_trip_interests_alter_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team11_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='team11_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
