# Generated by Django 4.2.27 on 2026-02-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('origin_city_id', models.IntegerField(blank=True, null=True)),
                ('destination_city_id', models.IntegerField(blank=True, null=True)),
                ('destination_name', models.CharField(max_length=200)),
                ('region_id', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_level', models.CharField(choices=[('ECONOMY', 'Economy'), ('MODERATE', 'Moderate'), ('LUXURY', 'Luxury')], default='MODERATE', max_length=20)),
                ('travelers_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trip Requirements',
                'db_table': 'trip_requirements',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('destination_name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('NEEDS_REGENERATION', 'Needs Regeneration')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='team10.triprequirements')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='team10.triprequirements')),
            ],
            options={
                'db_table': 'preference_constraints',
            },
        ),
        migrations.CreateModel(
            name='HotelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('rooms_count', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_schedules', to='team10.trip')),
            ],
            options={
                'db_table': 'hotel_schedules',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('facility_id', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activity_type', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing'), ('FOOD', 'Food'), ('SHOPPING', 'Shopping'), ('OUTDOOR', 'Outdoor'), ('CULTURE', 'Culture'), ('RELAX', 'Relax'), ('NIGHTLIFE', 'Nightlife'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('place_source_type', models.CharField(choices=[('WIKI', 'Wiki'), ('RECOMMENDATION', 'Recommendation'), ('FACILITIES', 'Facilities'), ('MANUAL', 'Manual'), ('EVENT', 'Event')], max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='team10.trip')),
            ],
            options={
                'db_table': 'daily_plans',
                'ordering': ['start_at'],
            },
        ),
    ]
