# Generated by Django 4.2.27 on 2026-02-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequirements',
            name='origin_city_id',
        ),
    ]
