# Generated by Django 4.2.27 on 2026-02-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team10', '0002_remove_triprequirements_origin_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_facility_id', models.IntegerField()),
                ('to_facility_id', models.IntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('transport_mode', models.CharField(choices=[('WALKING', 'پیاده\u200cروی'), ('DRIVING', 'خودرو شخصی'), ('PUBLIC_TRANSIT', 'حمل\u200cونقل عمومی'), ('TAXI', 'تاکسی')], default='WALKING', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transfer_time', models.DateTimeField()),
                ('from_daily_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='team10.dailyplan')),
                ('to_daily_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='team10.dailyplan')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_plans', to='team10.trip')),
            ],
            options={
                'db_table': 'transfer_plans',
                'ordering': ['transfer_time'],
            },
        ),
    ]
