# Generated by Django 4.2.27 on 2026-02-11 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id_article', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('title_fa', models.TextField()),
                ('title_en', models.TextField(blank=True, null=True)),
                ('body_fa', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('author_user_id', models.UUIDField(null=True)),
                ('last_editor_user_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('quality_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('quality_count', models.IntegerField(default=0)),
                ('current_revision_no', models.IntegerField(default=1)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'wiki_articles',
            },
        ),
        migrations.CreateModel(
            name='WikiTag',
            fields=[
                ('id_tag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title_fa', models.TextField()),
                ('title_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tags', models.ManyToManyField(blank=True, to='team6.wikitag')),
            ],
            options={
                'db_table': 'wiki_tags',
            },
        ),
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title_fa', models.TextField()),
                ('title_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team6.wikicategory')),
            ],
            options={
                'db_table': 'wiki_categories',
            },
        ),
        migrations.CreateModel(
            name='WikiArticleRef',
            fields=[
                ('id_ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('url', models.URLField()),
                ('publisher', models.TextField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'wiki_article_refs',
            },
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team6.wikicategory'),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='team6.wikitag'),
        ),
        migrations.CreateModel(
            name='WikiArticleRevision',
            fields=[
                ('id_revision', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.IntegerField()),
                ('editor_user_id', models.UUIDField(null=True)),
                ('change_note', models.TextField(null=True)),
                ('body_fa', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'wiki_article_revisions',
                'unique_together': {('article', 'revision_no')},
            },
        ),
        migrations.CreateModel(
            name='WikiArticleReports',
            fields=[
                ('id_report', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_user_id', models.UUIDField()),
                ('report_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'wiki_article_reports',
                'indexes': [models.Index(fields=['status', 'created_at'], name='wiki_articl_status_8109ed_idx')],
                'unique_together': {('article', 'reporter_user_id')},
            },
        ),
        migrations.CreateModel(
            name='WikiArticleLink',
            fields=[
                ('id_link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='team6.wikiarticle')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'wiki_article_links',
                'unique_together': {('from_article', 'to_article')},
            },
        ),
        migrations.CreateModel(
            name='ArticleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('notification_type', models.CharField(choices=[('edit', 'ویرایش متن'), ('image', 'افزودن/تغییر تصویر'), ('tags', 'تغییر برچسب'), ('category', 'تغییر دسته'), ('new', 'مقاله جدید')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'article_notifications',
                'indexes': [models.Index(fields=['user_id', 'is_read', 'created_at'], name='article_not_user_id_b88883_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('notify', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team6.wikiarticle')),
            ],
            options={
                'db_table': 'article_follows',
                'unique_together': {('user_id', 'article')},
            },
        ),
    ]
