# Generated by Django 4.2.27 on 2026-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikitag',
            name='slug',
            field=models.SlugField(),
        ),
    ]
