# Generated by Django 6.0.2 on 2026-02-09 16:10

import django.core.validators
import django.db.models.deletion
import team4.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='نام انگلیسی')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
                'db_table': 'facilities_amenity',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('location', team4.fields.PointField(verbose_name='موقعیت جغرافیایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'db_table': 'facilities_city',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='نام انگلیسی')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='خدمات اضطراری')),
                ('marker_color', models.CharField(choices=[('blue', 'آبی'), ('red', 'قرمز'), ('green', 'سبز'), ('orange', 'نارنجی'), ('purple', 'بنفش'), ('yellow', 'زرد')], default='blue', max_length=20, verbose_name='رنگ نشانگر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'db_table': 'facilities_category',
                'indexes': [models.Index(fields=['name_en'], name='idx_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('fac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=200, verbose_name='نام انگلیسی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('location', team4.fields.PointField(verbose_name='موقعیت جغرافیایی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز میانگین')),
                ('review_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد نظرات')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('is_24_hour', models.BooleanField(default=False, verbose_name='24 ساعته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='team4.category', verbose_name='دسته\u200cبندی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='team4.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
                'db_table': 'facilities_facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team4.amenity', verbose_name='امکانات')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team4.facility', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'امکانات مکان',
                'verbose_name_plural': 'امکانات مکان\u200cها',
                'db_table': 'facilities_facility_amenity',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='facilities', through='team4.FacilityAmenity', to='team4.amenity', verbose_name='امکانات'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500, verbose_name='URL تصویر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team4.facility', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 'facilities_image',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('Hourly', 'ساعتی'), ('Daily', 'روزانه'), ('Monthly', 'ماهانه'), ('Per Night', 'هر شب'), ('Per Session', 'هر جلسه')], max_length=50, verbose_name='نوع قیمت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_set', to='team4.facility', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت\u200cها',
                'db_table': 'facilities_pricing',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='نام انگلیسی')),
                ('location', team4.fields.PointField(blank=True, null=True, verbose_name='موقعیت جغرافیایی مرکز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'db_table': 'facilities_province',
                'indexes': [models.Index(fields=['name_en'], name='idx_province_name_en')],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='team4.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('location', team4.fields.PointField(blank=True, null=True, verbose_name='موقعیت جغرافیایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='team4.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'روستا',
                'verbose_name_plural': 'روستاها',
                'db_table': 'facilities_village',
            },
        ),
        migrations.AddIndex(
            model_name='facilityamenity',
            index=models.Index(fields=['facility'], name='idx_fac_amenity_fac'),
        ),
        migrations.AddIndex(
            model_name='facilityamenity',
            index=models.Index(fields=['amenity'], name='idx_fac_amenity_amenity'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityamenity',
            unique_together={('facility', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['category'], name='idx_facility_category'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['city'], name='idx_facility_city'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['status'], name='idx_facility_status'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('name_en', 'city')},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['facility'], name='idx_image_fac'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['facility', 'is_primary'], name='idx_image_primary'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['facility'], name='idx_pricing_fac'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='idx_city_province'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name_en')},
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['city'], name='idx_village_city'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['name_en'], name='idx_village_name_en'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('city', 'name_en')},
        ),
    ]
