# Generated by Django 4.2.27 on 2026-02-09 06:14

from django.db import migrations, models
import django.db.models.deletion
import team4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team4', '0003_province_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('location', team4.fields.PointField(blank=True, null=True, verbose_name='موقعیت جغرافیایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='team4.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'روستا',
                'verbose_name_plural': 'روستاها',
                'db_table': 'facilities_village',
                'indexes': [models.Index(fields=['city'], name='idx_village_city'), models.Index(fields=['name_en'], name='idx_village_name_en')],
                'unique_together': {('city', 'name_en')},
            },
        ),
    ]
