# Generated by Django 6.0.2 on 2026-02-09 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team4', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='team4.facility', verbose_name='مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'db_table': 'facilities_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_favorite_user'), models.Index(fields=['facility'], name='idx_favorite_facility'), models.Index(fields=['-created_at'], name='idx_favorite_created')],
                'unique_together': {('user', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='team4.facility', verbose_name='مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'db_table': 'facilities_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_review_user'), models.Index(fields=['facility'], name='idx_review_facility'), models.Index(fields=['-created_at'], name='idx_review_created'), models.Index(fields=['is_approved'], name='idx_review_approved')],
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
