# Generated by Django 4.2.27 on 2026-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team4', '0005_favorite_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='price_tier',
            field=models.CharField(choices=[('unknown', 'نامشخص'), ('free', 'رایگان'), ('budget', 'اقتصادی'), ('moderate', 'متوسط'), ('expensive', 'گران'), ('luxury', 'لوکس')], default='unknown', max_length=20, verbose_name='سطح قیمت'),
        ),
    ]
