# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import facility_pb2 as facility__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in facility_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FacilityServiceStub(object):
    """-----------------------------------------------------------------------------
    Facility Service Definition
    -----------------------------------------------------------------------------

    FacilityService acts as the "Source of Truth" for physical locations,
    operational data (hours, prices), and geographical hierarchies.
    It is responsible for Discovery and Logistics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchRegions = channel.unary_unary(
                '/facility.v1.FacilityService/SearchRegions',
                request_serializer=facility__pb2.SearchRegionsRequest.SerializeToString,
                response_deserializer=facility__pb2.SearchRegionsResponse.FromString,
                _registered_method=True)
        self.GetLocationHierarchy = channel.unary_unary(
                '/facility.v1.FacilityService/GetLocationHierarchy',
                request_serializer=facility__pb2.GetLocationHierarchyRequest.SerializeToString,
                response_deserializer=facility__pb2.GetLocationHierarchyResponse.FromString,
                _registered_method=True)
        self.GetPlacesInRegion = channel.unary_unary(
                '/facility.v1.FacilityService/GetPlacesInRegion',
                request_serializer=facility__pb2.GetPlacesInRegionRequest.SerializeToString,
                response_deserializer=facility__pb2.GetPlacesInRegionResponse.FromString,
                _registered_method=True)
        self.GetNearbyPlaces = channel.unary_unary(
                '/facility.v1.FacilityService/GetNearbyPlaces',
                request_serializer=facility__pb2.GetNearbyPlacesRequest.SerializeToString,
                response_deserializer=facility__pb2.GetNearbyPlacesResponse.FromString,
                _registered_method=True)
        self.GetPlaceByIds = channel.unary_unary(
                '/facility.v1.FacilityService/GetPlaceByIds',
                request_serializer=facility__pb2.GetPlaceByIdsRequest.SerializeToString,
                response_deserializer=facility__pb2.GetPlaceByIdsResponse.FromString,
                _registered_method=True)
        self.GetTravelEstimates = channel.unary_unary(
                '/facility.v1.FacilityService/GetTravelEstimates',
                request_serializer=facility__pb2.GetTravelEstimatesRequest.SerializeToString,
                response_deserializer=facility__pb2.GetTravelEstimatesResponse.FromString,
                _registered_method=True)


class FacilityServiceServicer(object):
    """-----------------------------------------------------------------------------
    Facility Service Definition
    -----------------------------------------------------------------------------

    FacilityService acts as the "Source of Truth" for physical locations,
    operational data (hours, prices), and geographical hierarchies.
    It is responsible for Discovery and Logistics.
    """

    def SearchRegions(self, request, context):
        """-------------------------
        1. Region Management
        -------------------------

        Searches for geographical regions (Cities, Provinces, Villages) based on a query string.
        Used for autocomplete or search bars where user selects a destination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationHierarchy(self, request, context):
        """Converts geographical coordinates (Lat/Lng) into a hierarchical Region structure.
        Useful for "What is here?" functionality or reverse geocoding.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlacesInRegion(self, request, context):
        """-------------------------
        2. Place Discovery & Details
        -------------------------

        Retrieves a list of places (attractions) within a specific Region ID.
        This method returns lightweight Place objects suitable for listing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNearbyPlaces(self, request, context):
        """Discovers places around a specific center point within a given radius.
        Useful for "Near Me" functionality. Returns places with calculated distances.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaceByIds(self, request, context):
        """Retrieves detailed operational information for a specific list of Place IDs.
        Used to fetch details like opening hours, prices, and contact info for selected candidates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTravelEstimates(self, request, context):
        """-------------------------
        3. Logistics
        -------------------------

        Calculates travel estimates (time, distance) and identifies settlements along the route.
        Essential for itinerary planning and suggesting stopovers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRegions,
                    request_deserializer=facility__pb2.SearchRegionsRequest.FromString,
                    response_serializer=facility__pb2.SearchRegionsResponse.SerializeToString,
            ),
            'GetLocationHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationHierarchy,
                    request_deserializer=facility__pb2.GetLocationHierarchyRequest.FromString,
                    response_serializer=facility__pb2.GetLocationHierarchyResponse.SerializeToString,
            ),
            'GetPlacesInRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlacesInRegion,
                    request_deserializer=facility__pb2.GetPlacesInRegionRequest.FromString,
                    response_serializer=facility__pb2.GetPlacesInRegionResponse.SerializeToString,
            ),
            'GetNearbyPlaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNearbyPlaces,
                    request_deserializer=facility__pb2.GetNearbyPlacesRequest.FromString,
                    response_serializer=facility__pb2.GetNearbyPlacesResponse.SerializeToString,
            ),
            'GetPlaceByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaceByIds,
                    request_deserializer=facility__pb2.GetPlaceByIdsRequest.FromString,
                    response_serializer=facility__pb2.GetPlaceByIdsResponse.SerializeToString,
            ),
            'GetTravelEstimates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTravelEstimates,
                    request_deserializer=facility__pb2.GetTravelEstimatesRequest.FromString,
                    response_serializer=facility__pb2.GetTravelEstimatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facility.v1.FacilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('facility.v1.FacilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FacilityService(object):
    """-----------------------------------------------------------------------------
    Facility Service Definition
    -----------------------------------------------------------------------------

    FacilityService acts as the "Source of Truth" for physical locations,
    operational data (hours, prices), and geographical hierarchies.
    It is responsible for Discovery and Logistics.
    """

    @staticmethod
    def SearchRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/SearchRegions',
            facility__pb2.SearchRegionsRequest.SerializeToString,
            facility__pb2.SearchRegionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocationHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/GetLocationHierarchy',
            facility__pb2.GetLocationHierarchyRequest.SerializeToString,
            facility__pb2.GetLocationHierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlacesInRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/GetPlacesInRegion',
            facility__pb2.GetPlacesInRegionRequest.SerializeToString,
            facility__pb2.GetPlacesInRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNearbyPlaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/GetNearbyPlaces',
            facility__pb2.GetNearbyPlacesRequest.SerializeToString,
            facility__pb2.GetNearbyPlacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaceByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/GetPlaceByIds',
            facility__pb2.GetPlaceByIdsRequest.SerializeToString,
            facility__pb2.GetPlaceByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTravelEstimates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/facility.v1.FacilityService/GetTravelEstimates',
            facility__pb2.GetTravelEstimatesRequest.SerializeToString,
            facility__pb2.GetTravelEstimatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
