# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import recom_pb2 as recom__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RecommendationServiceStub(object):
    """-----------------------------------------------------------------------------
    Recommendation Service Definition
    -----------------------------------------------------------------------------

    RecommendationService is responsible for ranking and personalization.
    It uses a "Candidate Generation & Re-ranking" strategy.
    It does NOT hold physical data about places, but scores them based on User Preferences.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreCandidates = channel.unary_unary(
                '/recommendation.v1.RecommendationService/ScoreCandidates',
                request_serializer=recom__pb2.ScoreCandidatesRequest.SerializeToString,
                response_deserializer=recom__pb2.ScoreCandidatesResponse.FromString,
                _registered_method=True)
        self.SuggestDestinations = channel.unary_unary(
                '/recommendation.v1.RecommendationService/SuggestDestinations',
                request_serializer=recom__pb2.SuggestDestinationsRequest.SerializeToString,
                response_deserializer=recom__pb2.SuggestDestinationsResponse.FromString,
                _registered_method=True)
        self.SuggestByRegion = channel.unary_unary(
                '/recommendation.v1.RecommendationService/SuggestByRegion',
                request_serializer=recom__pb2.SuggestByRegionRequest.SerializeToString,
                response_deserializer=recom__pb2.SuggestByRegionResponse.FromString,
                _registered_method=True)
        self.RecordInteraction = channel.unary_unary(
                '/recommendation.v1.RecommendationService/RecordInteraction',
                request_serializer=recom__pb2.RecordInteractionRequest.SerializeToString,
                response_deserializer=recom__pb2.RecordInteractionResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """-----------------------------------------------------------------------------
    Recommendation Service Definition
    -----------------------------------------------------------------------------

    RecommendationService is responsible for ranking and personalization.
    It uses a "Candidate Generation & Re-ranking" strategy.
    It does NOT hold physical data about places, but scores them based on User Preferences.
    """

    def ScoreCandidates(self, request, context):
        """Scores a list of candidate Place IDs based on user profile and context.
        Used by Trip Plan service to re-rank available places.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestDestinations(self, request, context):
        """Suggests general destinations (Regions) for a user (Cold Start/Inspiration).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestByRegion(self, request, context):
        """Suggests the top-rated places within a specific region for the user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordInteraction(self, request, context):
        """Records user feedback (View, Click, Add, Reject) to improve the ML model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreCandidates,
                    request_deserializer=recom__pb2.ScoreCandidatesRequest.FromString,
                    response_serializer=recom__pb2.ScoreCandidatesResponse.SerializeToString,
            ),
            'SuggestDestinations': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestDestinations,
                    request_deserializer=recom__pb2.SuggestDestinationsRequest.FromString,
                    response_serializer=recom__pb2.SuggestDestinationsResponse.SerializeToString,
            ),
            'SuggestByRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestByRegion,
                    request_deserializer=recom__pb2.SuggestByRegionRequest.FromString,
                    response_serializer=recom__pb2.SuggestByRegionResponse.SerializeToString,
            ),
            'RecordInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordInteraction,
                    request_deserializer=recom__pb2.RecordInteractionRequest.FromString,
                    response_serializer=recom__pb2.RecordInteractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """-----------------------------------------------------------------------------
    Recommendation Service Definition
    -----------------------------------------------------------------------------

    RecommendationService is responsible for ranking and personalization.
    It uses a "Candidate Generation & Re-ranking" strategy.
    It does NOT hold physical data about places, but scores them based on User Preferences.
    """

    @staticmethod
    def ScoreCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/ScoreCandidates',
            recom__pb2.ScoreCandidatesRequest.SerializeToString,
            recom__pb2.ScoreCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestDestinations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/SuggestDestinations',
            recom__pb2.SuggestDestinationsRequest.SerializeToString,
            recom__pb2.SuggestDestinationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestByRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/SuggestByRegion',
            recom__pb2.SuggestByRegionRequest.SerializeToString,
            recom__pb2.SuggestByRegionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/RecordInteraction',
            recom__pb2.RecordInteractionRequest.SerializeToString,
            recom__pb2.RecordInteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
