# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trip_pb2 as trip__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TripServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTrip = channel.unary_unary(
                '/trip.TripService/CreateTrip',
                request_serializer=trip__pb2.CreateTripRequest.SerializeToString,
                response_deserializer=trip__pb2.TripResponse.FromString,
                _registered_method=True)
        self.ListTrips = channel.unary_unary(
                '/trip.TripService/ListTrips',
                request_serializer=trip__pb2.Empty.SerializeToString,
                response_deserializer=trip__pb2.TripListResponse.FromString,
                _registered_method=True)


class TripServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TripServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrip,
                    request_deserializer=trip__pb2.CreateTripRequest.FromString,
                    response_serializer=trip__pb2.TripResponse.SerializeToString,
            ),
            'ListTrips': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrips,
                    request_deserializer=trip__pb2.Empty.FromString,
                    response_serializer=trip__pb2.TripListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trip.TripService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trip.TripService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TripService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trip.TripService/CreateTrip',
            trip__pb2.CreateTripRequest.SerializeToString,
            trip__pb2.TripResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trip.TripService/ListTrips',
            trip__pb2.Empty.SerializeToString,
            trip__pb2.TripListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
