# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import wiki_pb2 as wiki__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in wiki_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WikiServiceStub(object):
    """-----------------------------------------------------------------------------
    Wiki Service Definition
    -----------------------------------------------------------------------------

    WikiService is the content delivery network for the system.
    It is responsible for serving rich text descriptions and media assets (Images/Videos).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlaceBriefs = channel.unary_unary(
                '/wiki.v1.WikiService/GetPlaceBriefs',
                request_serializer=wiki__pb2.GetPlaceBriefsRequest.SerializeToString,
                response_deserializer=wiki__pb2.GetPlaceBriefsResponse.FromString,
                _registered_method=True)


class WikiServiceServicer(object):
    """-----------------------------------------------------------------------------
    Wiki Service Definition
    -----------------------------------------------------------------------------

    WikiService is the content delivery network for the system.
    It is responsible for serving rich text descriptions and media assets (Images/Videos).
    """

    def GetPlaceBriefs(self, request, context):
        """Retrieves brief information (Summary + Media) for a list of places.
        Used to populate UI cards in the Trip Planner.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WikiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlaceBriefs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaceBriefs,
                    request_deserializer=wiki__pb2.GetPlaceBriefsRequest.FromString,
                    response_serializer=wiki__pb2.GetPlaceBriefsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wiki.v1.WikiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wiki.v1.WikiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WikiService(object):
    """-----------------------------------------------------------------------------
    Wiki Service Definition
    -----------------------------------------------------------------------------

    WikiService is the content delivery network for the system.
    It is responsible for serving rich text descriptions and media assets (Images/Videos).
    """

    @staticmethod
    def GetPlaceBriefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wiki.v1.WikiService/GetPlaceBriefs',
            wiki__pb2.GetPlaceBriefsRequest.SerializeToString,
            wiki__pb2.GetPlaceBriefsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
