from django.urls import path
from . import views

app_name = "team13"

urlpatterns = [
    path("", views.base, name="index"),
    path("ping/", views.ping, name="ping"),
    path("places/", views.place_list, name="place_list"),
    path("places/<uuid:place_id>/", views.place_detail, name="place_detail"),
    path("places/<uuid:place_id>/rate/", views.place_rate, name="place_rate"),
    path("places/<uuid:place_id>/add-image/", views.place_add_image, name="place_add_image"),
    path("places/<uuid:place_id>/add-comment/", views.place_add_comment, name="place_add_comment"),
    path("nearest-place/", views.nearest_place, name="nearest_place"),
    path("events/", views.event_list, name="event_list"),
    path("events/<uuid:event_id>/", views.event_detail, name="event_detail"),
    path("events/<uuid:event_id>/rate/", views.event_rate, name="event_rate"),
    path("routes/", views.route_request, name="routes"),
    path("tsp/", views.tsp_request, name="tsp"),
    path("distance-matrix/", views.distance_matrix_request, name="distance_matrix"),
    path("isochrone/", views.isochrone_request, name="isochrone"),
    path("map-matching/", views.map_matching_request, name="map_matching"),
    path("search-places/", views.search_places, name="search_places"),
    path("neshan-search/", views.neshan_search, name="neshan_search"),
    path("reverse-geocode/", views.reverse_geocode_view, name="reverse_geocode"),
    path("geocode/", views.geocode_view, name="geocode"),
    path("places-in-radius/", views.places_in_radius, name="places_in_radius"),
    path("emergency/", views.emergency_nearby, name="emergency"),
    path("contribution/", views.submit_contribution, name="submit_contribution"),
    path("route-contribution/", views.submit_route_contribution, name="submit_route_contribution"),
    path("contribution-image/<str:filename>/", views.serve_contribution_image, name="serve_contribution_image"),
    path("admin/", views.team13_admin_dashboard, name="team13_admin_dashboard"),
    path("admin-panel/", views.team13_admin_dashboard, name="team13_admin_panel"),
    path("admin/approve/<uuid:contribution_id>/", views.team13_admin_approve, name="team13_admin_approve"),
    path("admin/reject/<uuid:contribution_id>/", views.team13_admin_reject, name="team13_admin_reject"),
    path("admin/approve-route/<uuid:contribution_id>/", views.team13_admin_approve_route, name="team13_admin_approve_route"),
    path("admin/reject-route/<uuid:contribution_id>/", views.team13_admin_reject_route, name="team13_admin_reject_route"),
    path("admin/approve-comment/<uuid:comment_id>/", views.team13_admin_approve_comment, name="team13_admin_approve_comment"),
    path("admin/reject-comment/<uuid:comment_id>/", views.team13_admin_reject_comment, name="team13_admin_reject_comment"),
    path("admin/approve-image/<uuid:image_id>/", views.team13_admin_approve_image, name="team13_admin_approve_image"),
    path("admin/reject-image/<uuid:image_id>/", views.team13_admin_reject_image, name="team13_admin_reject_image"),
    path("admin/add-admin/", views.team13_admin_add_admin, name="team13_admin_add_admin"),
]